// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt7AsFANRTAhLjwuVDkX4etTGdAFS8KvE',
    appId: '1:605351082868:web:e9909c66dccc131f3d0a21',
    messagingSenderId: '605351082868',
    projectId: 'firstproject-ee5ac',
    authDomain: 'firstproject-ee5ac.firebaseapp.com',
    storageBucket: 'firstproject-ee5ac.firebasestorage.app',
    measurementId: 'G-LPVKLLW7SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGSGZw2L5MPc_m7hXpzyBPeb1tzajZ-7g',
    appId: '1:605351082868:android:0217efd15644bc1a3d0a21',
    messagingSenderId: '605351082868',
    projectId: 'firstproject-ee5ac',
    storageBucket: 'firstproject-ee5ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV82woF1AYKbfzhV8cjH7pT91S2i_q_FE',
    appId: '1:605351082868:ios:5a159f5b8b3b54f73d0a21',
    messagingSenderId: '605351082868',
    projectId: 'firstproject-ee5ac',
    storageBucket: 'firstproject-ee5ac.firebasestorage.app',
    iosBundleId: 'com.example.mytestapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV82woF1AYKbfzhV8cjH7pT91S2i_q_FE',
    appId: '1:605351082868:ios:5a159f5b8b3b54f73d0a21',
    messagingSenderId: '605351082868',
    projectId: 'firstproject-ee5ac',
    storageBucket: 'firstproject-ee5ac.firebasestorage.app',
    iosBundleId: 'com.example.mytestapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt7AsFANRTAhLjwuVDkX4etTGdAFS8KvE',
    appId: '1:605351082868:web:4423fe34ce62aa983d0a21',
    messagingSenderId: '605351082868',
    projectId: 'firstproject-ee5ac',
    authDomain: 'firstproject-ee5ac.firebaseapp.com',
    storageBucket: 'firstproject-ee5ac.firebasestorage.app',
    measurementId: 'G-RPC2NTGJYC',
  );
}
